import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="bg-green-500 h-14 flex items-center justify-center">
          <h1 className="text-white text-2xl font-bold"> GoodVibesHub 🤗 </h1>
        </div>
        {children}
      </body>
    </html>
  );
}
